--- 
clone: 
  depth: 1
kind: pipeline
name : OldCam
version: XTREME-OLD
steps:
 - name: Xtreme
   image: panchajanya1999/archlinux:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - bash build --old

---
clone:
  depth: 1
kind: pipeline
name : NewCam
version: XTREME-NEW
steps:
 - name: Xtreme
   image: panchajanya1999/archlinux:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - bash build --new

---
kind: pipeline
name : Qti-Old
version: XTREME-QTI-OLD
steps:
 - name: Xtreme
   image: panchajanya1999/archlinux:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - bash build --qti
